### ISSUE TITLE
Everything isn't working except join and leave messages.

### ISSUE THREAD

**Issue by JJBZ03** [Efnilite/WorldServer#3]
Tab list is not working, per world chat is not working, and I don't know about economy because I don't use economy plugins. This is all on 1.9.0. I have the vilib 1.2.0 so I know it isn't that. I tried joining the discord first to report but it didn't let me join.

**Comment by Efnilite** [comment]
Are there any errors on startup? You can join the dc at https://www.efnilite.dev/discord

**Comment by JJBZ03** [comment]
Yes there is an error

`[00:15:53] [Server thread/INFO]: [WorldServer] Enabling WorldServer v1.9.0
[00:15:53] [Server thread/ERROR]: Error occurred while enabling WorldServer v1.9.0 (Is it up to date?)
java.util.NoSuchElementException: Unknown path chat-blocked in config.ymlat dev.efnilite.worldserver.config.Config.check(Config.java:204) ~[?:?]at dev.efnilite.worldserver.config.Config.getStringList(Config.java:157) ~[?:?]at dev.efnilite.worldserver.config.Option.init(Option.java:76) ~[?:?]
at dev.efnilite.worldserver.config.Config.reload(Config.java:35) ~[?:?]at dev.efnilite.worldserver.WorldServer.enable(WorldServer.java:99) ~[?:?]at dev.efnilite.vilib.ViPlugin.onEnable(ViPlugin.java:59) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b5 65e-c1279f7]at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]
at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]
at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by JJBZ03** [comment]
> You can join the dc at https://www.efnilite.dev/discord

Also the link works but when I try to join it says "unable to accept invite." Am I banned or something?

**Comment by Efnilite** [comment]
> Yes there is an error
> 
> `[00:15:53] [Server thread/INFO]: [WorldServer] Enabling WorldServer v1.9.0 [00:15:53] [Server thread/ERROR]: Error occurred while enabling WorldServer v1.9.0 (Is it up to date?) java.util.NoSuchElementException: Unknown path chat-blocked in config.ymlat dev.efnilite.worldserver.config.Config.check(Config.java:204) ~[?:?]at dev.efnilite.worldserver.config.Config.getStringList(Config.java:157) ~[?:?]at dev.efnilite.worldserver.config.Option.init(Option.java:76) ~[?:?] at dev.efnilite.worldserver.config.Config.reload(Config.java:35) ~[?:?]at dev.efnilite.worldserver.WorldServer.enable(WorldServer.java:99) ~[?:?]at dev.efnilite.vilib.ViPlugin.onEnable(ViPlugin.java:59) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b5 65e-c1279f7]at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Can you send your config.yml?

**Comment by Efnilite** [comment]
> > You can join the dc at https://www.efnilite.dev/discord
> 
> Also the link works but when I try to join it says "unable to accept invite." Am I banned or something?

It seems your Discord account was compromized some time ago, so I had to ban you to remove the spam messages. I'll unban you now.

**Comment by JJBZ03** [comment]
> Can you send your config.yml?

My config.yml

`#====================================================================================================================================#
#                                                                                                                                    #
#     :::       :::  ::::::::  :::::::::  :::        :::::::::   ::::::::  :::::::::: :::::::::  :::     ::: :::::::::: :::::::::    #
#     :+:       :+: :+:    :+: :+:    :+: :+:        :+:    :+: :+:    :+: :+:        :+:    :+: :+:     :+: :+:        :+:    :+:   #
#    +:+       +:+ +:+    +:+ +:+    +:+ +:+        +:+    +:+ +:+        +:+        +:+    +:+ +:+     +:+ +:+        +:+    +:+    #
#   +#+  +:+  +#+ +#+    +:+ +#++:++#:  +#+        +#+    +:+ +#++:++#++ +#++:++#   +#++:++#:  +#+     +:+ +#++:++#   +#++:++#:      #
#  +#+ +#+#+ +#+ +#+    +#+ +#+    +#+ +#+        +#+    +#+        +#+ +#+        +#+    +#+  +#+   +#+  +#+        +#+    +#+      #
#  #+#+# #+#+#  #+#    #+# #+#    #+# #+#        #+#    #+# #+#    #+# #+#        #+#    #+#   #+#+#+#   #+#        #+#    #+#       #
#  ###   ###    ########  ###    ### ########## #########   ########  ########## ###    ###     ###     ########## ###    ###        #
#                                                                                                                                    #
#====================================================================================================================================#

#====================================================================================================================================#
#                                                                                                                                    #
#                                            (c) Efnilite 2022-2023. Do not distribute!                                              #
#                                                                                                                                    #
#====================================================================================================================================#

# -= Auto updater =-
# The auto updater will automatically download updates if they are available.
# It's highly recommended to keep this on!
auto-updater: true

# -= /ws requires permission =-
# If true, using /ws requires the "ws" permission.
ws-requires-permission: false

# -= World groups =-
# Group together worlds to share the tab list and chat
# Have any questions? Join my Discord (https://discord.gg/wRpSWHx)
groups:
  lobby_group:
    - 'lobby'
    - 'lobby_nether'
    - 'lobby_end'
  potions_group:
    - 'potions'
    - 'potions_nether'
    - 'potions_end'
  potions_classic_group:
    - 'potions_classic'
    - 'potions_classic_nether'
    - 'potions_classic_end'
  elixir_group:
    - 'elixir'
    - 'elixir_nether'
    - 'elixir_end'
  grunker_group:
    - 'grunker'
    - 'grunker_nether'
    - 'grunker_end'
  blocktopia_group:
    - 'blocktopia'
    - 'blocktopia_nether'
    - 'blocktopia_end'
  jjcraft_group:
    - 'jjcraft'
    - 'jjcraft_nether'
    - 'jjcraft_end'
  joulesi_group:
    - 'joulesi'
    - 'joulesi_nether'
    - 'joulesi_the_end'
  yinzsteal_group:
    - 'yinzsteal'
    - 'yinzsteal_nether'
    - 'yinzsteal_end'
  frownet_lobby_group:
    - 'frownet_lobby'
    - 'frownet_lobby_nether'
    - 'frownet_lobby_end'

# -= Enable per world tab list =-
# True: players not in the same world will be hidden
# False: every player will be visible
tab-enabled: true

# -= Enable per world chat =-
# True: players not in the same world can't chat with each other
# False: chat will be global
chat-enabled: true

# -= Enable global chat =-
# True: players will be able to talk in global chat using a prefix
# False: players are bound to talk in their own world (if enabled)
global-chat-enabled: false

# -= Global chat prefix =-
# The prefix for global chat.
# This is used to be able to type in global chat.
# If you set this to '!', typing '!hello' will be seen by all players.
# This is not a command. Add the prefix (by default '!') in front of your message to access global chat!
global-chat-prefix: '!'

# -= Global chat format =-
# The text format when a message is sent in global chat
# Placeholders:
# %world% - The group/world in which the message was sent
# %player% - The player
# %message% - The message
# %prefix% - The player's prefix
# %suffix% - The player's suffix
global-chat-format: '[Global] <white>%player%: %message%'

# -= Spy Format =-
# The message format for when spy mode is enabled for an admin.
# Change this by using /ws menu.
# Placeholders:
# %world% - The group/world in which the message was sent
# %player% - The player
# %message% - The message
# %prefix% - The player's prefix
# %suffix% - The player's suffix
spy-format: '<#abcdef>(%world%) <gray>%player%: %message%'

# -= World chat format =-
# Change the chat format for a group of worlds or a specific world
# If conflict happens, groups are prioritized over worlds.
# These messages support PlaceholderAPI placeholders.
# Have any questions? Join my Discord (https://discord.gg/wRpSWHx)
# Learn more about colouring: https://docs.adventure.kyori.net/minimessage/format.html
# Placeholders:
# %world% - The group/world in which the message was sent
# %player% - The player
# %message% - The message
# %prefix% - The player's prefix
# %suffix% - The player's suffix
chat-format:
  lobby_group: '<%player%> %message%'
  potions_group: '<%player%> %message%'
  potions_classic_group: '<%player%> %message%'
  elixir_group: '<%player%> %message%'
  grunker_group: '<%player%> %message%'
  blocktopia_group: '<%player%> %message%'
  jjcraft_group: '<%player%> %message%'
  joulesi_group: '<%player%> %message%'
  yinzsteal_group: '<%player%> %message%'
  frownet_lobby_group: '<%player%> %message%'

# -= World chat cooldown =-
# The chat cooldown per world group or world.
# This is in seconds. Time cheat sheet:
# 1 minute = 60 seconds
# 1 hour = 3600 seconds
# 1 day = 86400 seconds
chat-cooldown:
  global: 0

# -= World chat cooldown format =-
# The message players get when they are on chat cooldown.
# Placeholders:
# %remaining% - the time remaining
# %time% - the total cooldown time
chat-cooldown-format: <gray>You need to wait <green>%remaining%<gray> seconds until
  you can send another message!

# -= Chat blocked =-
# Words which will be banned in chat.
# These are case-insensitive.
chat-blocked:

# -= Chat blocked format =-
# The message players get when their message contains a blocked word.
chat-blocked-format: <gray>You can't say mean things :(

# -= World chat join formats =-
# Add a custom join message per world chat.
# Placeholders:
# %player% - the player
# %prefix% - The player's prefix
# %suffix% - The player's suffix
chat-join-formats:

# -= World chat leave formats =-
# Add a custom leave message per world chat.
# Placeholders:
# %player% - the player
# %prefix% - The player's prefix
# %suffix% - The player's suffix
chat-leave-formats:

# -= Clear chat on switch =-
# If set to true, will clear the chat on a switch of the world.
clear-chat-on-switch: false

# -= Enable per world economy =-
# True: players will have a different balance, depending on which World or World Group they are in.
# False: players will share
economy-enabled: false

# -= Economy global =-
# True: the economy will be shared across the entire server
# False: if economy is enabled, each world or world group will have a different economy.
economy-global-enabled: false

# -= Economy switch notification =-
# True: players will receive a message when they switch worlds (or join) detailing how much balance they have
# False: players won't get a message
economy-switch-notification: false

# -= Economy balance notification format =-
# Set the format of the message players get if they switch worlds.
# This will only be set if economy and economy switch notifications are enabled.
# Placeholders:
# %amount% - the current amount
economy-switch-format: <white>You now have <#4DF019>â¬$%amount%<gray>.

# -= Economy currency symbol =-
# The economy currency symbol.
economy-currency-symbol: â¬$

# -= Economy currency names =-
# The names of the currency.
# The first entry is for singular, the second for plural.
economy-currency-names:
  - 'eurodollar'
  - 'eurodollars'

# -= Economy starting amount =-
# The amount of money the player will start with in a specific world group if they haven't ever joined that group.
economy-starting-amount:
  example: 1000
  MyWorld: 69.69

# -= Economy override balance command =-
# Whether WorldServer should register /bal and /balance.
# This will override any plugin who is already using this command.
# Requires a restart to take effect.
economy-override-balance-command: true

# -= Economy balance format =-
# The message format of the /bal command.
economy-balance-format: '%player% has â¬$%amount%'

# -= Economy balance change =-
# Sends a message to the player when their balance changes.
economy-balance-change: true

# -= Economy balance change format =-
# The message a player receives when their balance is changed.
# Placeholders:
# %amount% - the given amount.
# %prefix% - a + or -, depending on whether the amount is added or removed.
# Example: '%prefix%%amount% eurodollars' -> '+10 eurodollars'
economy-balance-change-format: <gray>%prefix%<white>%amount% eurodollars

# -= Economy override pay command =-
# Whether WorldServer should register /pay
# This will override any plugin who is already using this command.
# Requires a restart to take effect.
economy-override-pay-command: true

# -= Economy pay format =-
# These messages support PlaceholderAPI placeholders.
# Learn more about colouring: https://docs.adventure.kyori.net/minimessage/format.html

# The format for when a player does not have enough funds to pay someone.
economy-pay-no-funds-format: You don't have enough â¬$ to do that!
# The format for when a player sends another player money.
economy-pay-send-format: You sent %player% â¬$%amount%
# The format for when a player receives money from another player.
economy-pay-receive-format: '%player% sent you â¬$%amount%'

# -= Economy override baltop command =-
# Whether WorldServer should register /baltop and /balancetop
# This will override any plugin who is already using this command.
# Requires a restart to take effect.
economy-override-baltop-command: true
`

> > Yes there is an error
> > `[00:15:53] [Server thread/INFO]: [WorldServer] Enabling WorldServer v1.9.0 [00:15:53] [Server thread/ERROR]: Error occurred while enabling WorldServer v1.9.0 (Is it up to date?) java.util.NoSuchElementException: Unknown path chat-blocked in config.ymlat dev.efnilite.worldserver.config.Config.check(Config.java:204) ~[?:?]at dev.efnilite.worldserver.config.Config.getStringList(Config.java:157) ~[?:?]at dev.efnilite.worldserver.config.Option.init(Option.java:76) ~[?:?] at dev.efnilite.worldserver.config.Config.reload(Config.java:35) ~[?:?]at dev.efnilite.worldserver.WorldServer.enable(WorldServer.java:99) ~[?:?]at dev.efnilite.vilib.ViPlugin.onEnable(ViPlugin.java:59) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b5 65e-c1279f7]at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by JJBZ03** [comment]
> > Yes there is an error
> > `[00:15:53] [Server thread/INFO]: [WorldServer] Enabling WorldServer v1.9.0 [00:15:53] [Server thread/ERROR]: Error occurred while enabling WorldServer v1.9.0 (Is it up to date?) java.util.NoSuchElementException: Unknown path chat-blocked in config.ymlat dev.efnilite.worldserver.config.Config.check(Config.java:204) ~[?:?]at dev.efnilite.worldserver.config.Config.getStringList(Config.java:157) ~[?:?]at dev.efnilite.worldserver.config.Option.init(Option.java:76) ~[?:?] at dev.efnilite.worldserver.config.Config.reload(Config.java:35) ~[?:?]at dev.efnilite.worldserver.WorldServer.enable(WorldServer.java:99) ~[?:?]at dev.efnilite.vilib.ViPlugin.onEnable(ViPlugin.java:59) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:540) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:454) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b5 65e-c1279f7]at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7] at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3814-Spigot-64b565e-c1279f7]at java.lang.Thread.run(Thread.java:833) ~[?:?]`
> 
> Can you send your config.yml?

My config.yml
[config.yml.txt](https://github.com/Efnilite/WorldServer/files/11927757/config.yml.txt)

**Comment by Efnilite** [comment]
Try setting `chat-blocked: []` on your config and restart the server.

**Comment by JJBZ03** [comment]
> Try setting `chat-blocked: []` on your config and restart the server.

Now there is no error but it's still doing the same thing. Only leave and join messages are working. Also I forgot to mention it doesn't block vanilla leave and join messages if you are in a different group.

**Comment by JJBZ03** [comment]
> Try setting `chat-blocked: []` on your config and restart the server.

Never mind nothing is working at all it isn't even doing that. My players lied to me. They said it says left and join when I switch worlds but it doesn't. So basically the plugin does absolutely nothing.

**Comment by Efnilite** [comment]
I'll test your setup for myself tomorrow to see what's wrong

**Comment by JJBZ03** [comment]
I use Bungeecord could that be the problem?

**Comment by Efnilite** [comment]
It seems that you have several empty sections in your config. Try setting `chat-join-formats: []` and `chat-leave-formats: []`, followed by a restart. If this doesn't work, I'll test it myself. 

> I use Bungeecord could that be the problem?

No

**Comment by JJBZ03** [comment]
> It seems that you have several empty sections in your config. Try setting `chat-join-formats: []` and `chat-leave-formats: []`, followed by a restart. If this doesn't work, I'll test it myself.
> 
> > I use Bungeecord could that be the problem?
> 
> No

I added join and leave formats and it still doesn't work.

**Comment by JJBZ03** [comment]
My new config.yml

[config.yml.txt](https://github.com/Efnilite/WorldServer/files/11931272/config.yml.txt)
