### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by JJGaming0219** [Efnilite/WorldServer#4]
Hello,

Either I am not doing something right, or I am guessing another plugin might be interfering. I had just downloaded Vilib and WorldServer (already had vault installed), and I go in and start my server after putting the plugins into my folder. I start up my server, wait for it to be fully up, then try and type WS commands in chat, and I look in the plugins folder and I don't see a WS folder in there containing the config.

If you could help me that would be much appreciated. I wanna get this working on my server since I have 22 worlds currently I have to sort out and it's a huge pain already lol.

Thanks

JJ

**Comment by Kxsumi** [comment]
A log would help. 

https://mclo.gs

**Comment by JJGaming0219** [comment]
That was actually really helpful. I did find the issue with it. It seems the one I downloaded was not the right version, though I downloaded it from the github. Here's the log https://mclo.gs/LKGza3c#L2160

**Comment by JJGaming0219** [comment]
I do appreciate the help. I have found the issue and resolved it. Have a good one!
